### ISSUE TITLE
Permission 요청시 ActivityNotFoundException

### ISSUE THREAD

**Issue by usersiyang** [Volvo-Voice-Assistance/assistance-android#16]
@KDW03 님,

앱 실행 후 권한 요청시 아래와 같은 이유로 현재 AppCrash 발생하고 있습니다. 
혹시 테스트 단말에서는 해당 이슈가 없었는지 확인 부탁 드립니다.

FATAL EXCEPTION: main
    Process: com.volvo.assistanceandroid, PID: 31790
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=574735241, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.volvo.assistanceandroid/com.volvo.assistanceandroid.MainActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION dat=com.volvo.assistanceandroid.MainActivity }
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5368)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION dat=com.volvo.assistanceandroid.MainActivity }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2117)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1762)
    at android.app.Activity.startActivityForResult(Activity.java:5410)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
    at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:239)
    at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
    at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
    at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
    at com.volvo.assistanceandroid.MainActivity.checkPermission(MainActivity.kt:83)
    at com.volvo.assistanceandroid.MainActivity.requestPermissionLauncher$lambda-1(MainActivity.kt:29)
    at com.volvo.assistanceandroid.MainActivity.$r8$lambda$gCxy9wjYNd8hDKlDrtzoYyD8R6E(Unknown Source:0)
    at com.volvo.assistanceandroid.MainActivity$$ExternalSyntheticLambda2.onActivityResult(Unknown Source:4)
    at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
    at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
    at androidx.activity.ComponentActivity.onRequestPermissionsResult(ComponentActivity.java:667)
    at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:636)
    at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8535)
    at android.app.Activity.dispatchActivityResult(Activity.java:8392)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5361)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407) 
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) 
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loopOnce(Looper.java:201) 
    at android.os.Looper.loop(Looper.java:288) 
    at android.app.ActivityThread.main(ActivityThread.java:7870) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by KDW03** [comment]
제 테스트 단말에서는 해당 이슈가 발생되지 않았습니다
한번 해결 방법을 찾아보겠습니다.
근데 제가 다른 단말이 없어서 코드를 수정해도 해당 이슈가 해결되는지 확인할 수 없습니다.
혹시 해당 단말 대여는 안될까요?

**Comment by usersiyang** [comment]
단말 반출이 어려운 상태라 이슈 분석이 어려울 것 같네요. 
일단 차주 미팅 전까지 제가 좀 더 확인해 보도록 하겠습니다.

**Comment by jujuwon** [comment]
테스트 환경이 달라지면서 해결될 이슈로 판단되어 Close 하겠습니다 🙌
